#!/bin/sh

snippets_dir=~/".snp"

# Check for/create snippet dir
if [ ! -d $snippets_dir ]; then
    echo "ERROR: $snippets_dir doesn't exist."
    echo "Create it now? [y/n]"
    read yn
    if [[ $yn == "y" || $yn == "Y" ]]; then
        mkdir $snippets_dir
    else
        exit 1
    fi
fi

case $1 in
    l|list) # list
        echo "snp snippets:\n"
        echo "$(ls -R $snippets_dir)" ;;
    m|move) # move
        if [[ "$2" == "" && $3 == "" ]]; then
            echo "snp usage:\n"
            echo "snp move <name> <group>"
        elif [[ -e $snippets_dir/$2 ]]; then
            if -d $snippets_dir/$3 ]]; then
                mv $snippets_dir/$2 $snippets_dir/$3/$2
            else
                echo "MOVE TO ERROR: $snippets_dir/$3 is not a group."
                exit 1
            fi
        else
            echo "MOVE FROM ERROR: $2 is not a snippet."
            exit 1
        fi ;;
    n|new) # new
        if [[ "$2" == "" && "$3" == "" ]]; then
            echo "snp usage:\n"
            echo "snp new <name> \"<text>\""
            echo "snp new group <name>"
        elif [[ "$2" == "group" && "$3" != "" ]]; then
            mkdir $snippets_dir/$3
        else
            echo -n "$3" >> $snippets_dir/$2
        fi;;
    r|remove) # remove
        if [[ "$2" == "" ]]; then
            echo "snp usage:\n"
            echo "snp remove <name>"
            echo "snp remove group <name>"
        elif [[ "$2" == "group" ]]; then
            [[ "$3" != "" ]] && echo "REMOVE GROUP ERROR: $3 does not exist."
            rm -rf $snippets_dir/$3
        elif [[ "$2" != "" && -e $snippets_dir/$2 ]]; then
            rm $snippets_dir/$2
        else
            echo "REMOVE ERROR: Snippet $2 does not exist."
            exit 1
        fi ;;
    c|copy) # copy
        if [[ "$2" == "" ]]; then
            echo "snp usage:\n"
            echo "snp copy <name> # copy snippet (to clipboard)"
        elif [[ -e $snippets_dir/$2 ]]; then
            cat "$snippets_dir/$2" | pbcopy
            echo "Snippet text copied to clipboard."
        else
            echo "COPY ERROR: Snippet $2 does not exist."
            exit 1
        fi ;;
    *)
        echo "snp usage:\n"
        echo "snp new <name> \"<text>\"   # new snippet"
        echo "snp new group <name>      # new group"
        echo "snp list                  # list snippets"
        echo "snp move <name> <group>   # move"
        echo "snp remove <name>         # remove"
        echo "snp remove group <name>   # remove group"
        echo "snp copy <name>           # copy snippet (to clipboard)" ;;
esac

exit 0
